import Head from "next/head";
import styles from "../styles/index.module.css";
import Widgets from "../components/home/Widgets";
import GreetHome from "../components/home/GreetHome";
import PieChart from "../components/home/PieChart";
import Tables from "../components/home/Tables";
import ColumnGraph from "../components/home/ColumnGraph";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [Data, setData] = useState([]);

  useEffect(() => {
    const fetchAllData = async () => {
      try {
        const res = await axios.get("http://localhost:8000");
        setData(res.data);
      } catch (error) {
        console.log(error);
      }
    };
    fetchAllData();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200;300&family=Rubik:wght@400;500;600;700&display=swap" rel="stylesheet"></link> */}
      </Head>
      <div className={styles.homes_container}>
        <div className={styles.greet_container}>
          <GreetHome />
        </div>
        <div className={styles.homes_widgets}>
          <Widgets type="user" />
          <Widgets type="visits" />
          <Widgets type="ratio" />
          <Widgets type="gender" />
        </div>

        <div className={styles.homes_charts}>
          <ColumnGraph data={Data} />
          <PieChart data={Data} />
        </div>
        <div className={styles.table_heading}>
            Lastest Visitors
          </div>
        <div className={styles.table}>
          <Tables/>
        </div>
      </div>
    </>
  );
}
